openapi: 3.0.0
info:
  version: 1.0.0
  title: "Petstore example"
  description: "My pestore http application programming interface"
  license:
    name: MIT
servers:
- url: https://api.pestore.com/
paths:
  "/pets":
    $ref: "https://raw.githubusercontent.com/stubleapp/petstore/main/paths/pets/pets.yml"
  "/pets/:id":
    $ref: "https://raw.githubusercontent.com/stubleapp/petstore/main/paths/pets/pets$:id.yml"
components:
  schemas:
    Pagination:
      $ref: "https://raw.githubusercontent.com/stubleapp/petstore/main/components/schemas/pagination.yml"
    Pet:
      $ref: "https://raw.githubusercontent.com/stubleapp/petstore/main/components/schemas/pet.yml"
    Pets:
      $ref: "https://raw.githubusercontent.com/stubleapp/petstore/main/components/schemas/pets.yml"
  responses:
    Invalid:
      $ref: "https://raw.githubusercontent.com/stubleapp/petstore/main/components/responses/invalid.yml"
    Unauthorized:
      $ref: "https://raw.githubusercontent.com/stubleapp/petstore/main/components/responses/unauthorized.yml"
    Unauthenticated:
      $ref: "https://raw.githubusercontent.com/stubleapp/petstore/main/components/responses/unauthenticated.yml"
  parameters:
    Limit:
      $ref: "https://raw.githubusercontent.com/stubleapp/petstore/main/components/parameters/limit.yml"
